# Site settings
baseurl = "http://www.buzzwordizer.com/"
languageCode = "en-us"
title = "Buzzwordizer - Buzzwords As A Service"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-75586345-1"

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) or
    # most longer texts.
    #
    # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
    # for more icons. The icons are represented by their corresponding
    # CSS class.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Buzzwordizer"
    description = "Buzzwordizer delivers global cloudscale buzzwords"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "buzzwordizer@gmail.com"

    # Link custom assets relative to /static
    custom_css = []
    custom_js  = []


    # Navigation
    [params.navigation]
        brand = "Buzzwordizer"
        features = "Features"
        example = "Example"
        about = "About"
        contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    # [[menu.postpend]]
    #    url = "http://gohugo.io"
    #    name = "External link"
    #    weight = 10


    # Hero section
    [params.hero]
        # To change the background image of the hero, replace 'header-bg.jpg' in
        # the 'static/img' folder.
        title = "BUZZWORDIZER"
        subtitle = "Buzzwords As A Service"
        buttonText = "Go Cloudscale Now"


    # Features section
    [params.features]
        enable = true
        title = "Features"
        # subtitle = "Lorem ipsum dolor sit amet consectetur."

        [[params.features.row]]

            [[params.features.row.list]]
                icon = "fa-globe"
                title = "Enterprise Grade Buzzwords"
                description = "Don't choose between scaling up or scaling out. Choose cloudscale - for when webscale fails to perform to your needs. Always on continuous buzzword delivery. 999.999% uptime guaranteed."

            [[params.features.row.list]]
                icon = "fa-plug"
                title = "Powerful Microservice Integration"
                description = "Step up your service oriented architecture with the next generation cross platform API. Synergize with your existing infrastructure. Focus on your core competency and we'll deliver the bleeding edge buzzwords."

            [[params.features.row.list]]
                icon = "fa-heartbeat"
                title = "Unparalleled User Engagement"
                description = "Trying to grow your userbase? We've got you covered. Growth hacking isn't about creativity, it's about data driven buzzwords. Get ahead of the curve and beat out the competition with unrestricted tier one buzzwords."


    # Example section
    [params.example]
        enable = true
        title = "Example"
        subtitle = "Try It Now!"
        code = "curl -X POST http://api.buzzwordizer.com -H'Content-Type: application/json' -d'{\"input\": \"We are an IT company that makes server software\"}'"

    # About section
    [params.about]
        enable = true
        title = "About"
        subtitle = "Buzzwordizer has been the driving force and supplier behind this era's buzzwords. Here's a highlight of our accomplishments and successes."
        endpoint = "Be part<br>of our<br>story!"

        # The events will be listed from the top to the bottom.
        # All images are stored under 'static/img/about'.
        # Replace them with your own.
        [[params.about.events]]
            img = "1.jpg"
            date = "Late 2008"
            title = "Launch"
            description = "As the economy struggled, Buzzwordizer launched as a tool to help the recently unemployed seduce LinkedIn recruiters. Little did we know how far it would go."

        [[params.about.events]]
            img = "2.jpg"
            date = "2009"
            title = "\"The Cloud\""
            description = "During design planning, it became clear engineers were incapable of drawing servers, and their representations ended up looking like squiggly ovals. Realizing the liguistic market gap, we coined it \"the cloud\" and the industry adoped it."

        [[params.about.events]]
            img = "3.jpg"
            date = "Early 2010"
            title = "Opening Up Our \"Disruptive\" API"
            description = "Our public API went live. Buzzwordizer's immediate market success against it's larger competitors left us speechless. Realizing the potential of \"disruptive\", we adopted and pushed forward the term, leading by example."

        [[params.about.events]]
            img = "4.jpg"
            date = "Mid 2012"
            title = "\"Big Data\""
            description = "On the way to recovery from <a href='http://www.businessinsider.com/people-think-stormy-weather-affects-cloud-computing-2012-8'> the apparent confusion in what \"the cloud\" really was</a> , we wanted to keep our next mainstream buzzword so simple a five year old could understand it. Two syllables and seven letters later, and this cross industry term was everywhere."

        [[params.about.events]]
            img = "5.jpg"
            date = "Early 2014"
            title = "\"Growth Hacking\""
            description = "As we continued to expand into more diverse industries, we wanted a new term that included \"hack\", but was accessible by people whose understanding of hacking was limited to what they watched on CSI. \"Growth hacking\" was born, and it spread faster than you can say \"MongoDB is webscale\"."

        [[params.about.events]]
            img = "6.jpg"
            date = "Start of 2015"
            title = "\"Unicorn Startup\""
            description = "\"Unicorn Startup\" wasn't supposed to leave the Buzzwordizer linguistic research lab. It was a byproduct of brainstorming the most unrelated terms possible. However, it escaped into the public, and we decided to run with it."

    # Client section
    [params.clients_list]
        enable = false

        # All the clients' logos are stored under 'static/img/logos'.
        # Replace them with your clients's logos.
        [[params.clients]]
            logo = "1.jpg"
            link = "#"

        [[params.clients]]
            logo = "2.jpg"
            link = "#"

        [[params.clients]]
            logo = "3.jpg"
            link = "#"

        [[params.clients]]
            logo = "4.jpg"
            link = "#"


    # Contact section
    [params.contact]
        enable = true
        title = "Contact Us"
        subtitle  = "If you are looking for an enterprise or custom solution"
        buttonText = "Send message"

        # 'warning' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name *"
            warning = "Please enter your name."

        [params.contact.form.email]
            text = "Email *"
            warning = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone *"
            warning = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message *"
            warning = "Please enter a message."


    # Footer section
    [params.footer]
        enable = true
        copyright = "Buzzwordizer <i class='fa fa-trademark'></i> <i class='fa fa-copyright'></i> <i class='fa fa-registered'></i> All Rights Reserved <i class='fa fa-creative-commons'></i>"

        [[params.footer.social]]
            icon = "fa-github"
            link = "https://github.com/bengadbois/buzzwordizer"

        [[params.footer.social]]
            icon = "fa-area-chart"
            link = "https://buzzwordizer.statuspage.io/"
